name: 'ApyGuard API Security Scanner'
description: 'Scan APIs for security issues using ApyGuard'
inputs:
  api_key:
    description: 'ApyGuard API token'
    required: true
  task_id:
    description: 'Task ID from ApyGuard platform'
    required: true
  api_url:
    description: 'ApyGuard API endpoint URL'
    required: true
    default: 'https://api.apyguard.com/v1'
  severity_threshold:
    description: 'Severity threshold for the scan. Options are Critical, High, Medium, Low, Informational'
    required: true
    default: 'Medium'
  
runs:
  using: 'node16'
  main: 'dist/index.js'